// datasiswa.js
const daftarSiswa = [

    { username: "admin", password: "gsdiredja", nama: "ADMINISTRATOR", kelas: "ADMIN" },

    // KELAS XI-1
    { username: "ais754", password: "12345", nama: "AISYAH OKTA LIVINA LAURENZ", kelas: "XI-1" },
    { username: "aje214", password: "12345", nama: "AJENG ULANDARI", kelas: "XI-1" },
    { username: "aly125", password: "12345", nama: "ALYSA RANI ZALIANTI", kelas: "XI-1" },
    { username: "ame859", password: "12345", nama: "AMELIA JUNITA CAHYANI", kelas: "XI-1" },
    { username: "aur381", password: "12345", nama: "AURA CINTYA ARBIELA PUTRI", kelas: "XI-1" },
    { username: "azi350", password: "12345", nama: "AZIZIAH JACINDA RUELA MAHSA RAHMADI", kelas: "XI-1" },
    { username: "cac328", password: "12345", nama: "CACA HERLIANA PUTRI", kelas: "XI-1" },
    { username: "del242", password: "12345", nama: "DELA CAHYA MAULITA", kelas: "XI-1" },
    { username: "dev854", password: "12345", nama: "DEVI MARETA", kelas: "XI-1" },
    { username: "ega204", password: "12345", nama: "EGA FABIAN YAFA", kelas: "XI-1" },
    { username: "far792", password: "12345", nama: "FARELIO BRILYANSYAH", kelas: "XI-1" },
    { username: "flo858", password: "12345", nama: "FLORA AYU VALENCYA", kelas: "XI-1" },
    { username: "fre658", password: "12345", nama: "FREDYCO RAKA", kelas: "XI-1" },
    { username: "gil189", password: "12345", nama: "GILANG FITRAH DARMAWAN", kelas: "XI-1" },
    { username: "jay704", password: "12345", nama: "JAYANTI BUNGA LESTARI", kelas: "XI-1" },
    { username: "lea532", password: "12345", nama: "LEAVY AQEYLA AYATUL HUSNA", kelas: "XI-1" },
    { username: "mar132", password: "12345", nama: "MARVIN NAZALLUL ALVIZAR", kelas: "XI-1" },
    { username: "moh130", password: "12345", nama: "MOHM ANAS MALIKI", kelas: "XI-1" },
    { username: "mut195", password: "12345", nama: "MUTIARA SAFITRI MUSTOFA", kelas: "XI-1" },
    { username: "nab323", password: "12345", nama: "NABILA GABRELA PRADITA", kelas: "XI-1" },
    { username: "nab338", password: "12345", nama: "NABILA PUTRI AWALIA", kelas: "XI-1" },
    { username: "nai617", password: "12345", nama: "NAILA IZZA NURJANAH", kelas: "XI-1" },
    { username: "nai716", password: "12345", nama: "NAILA ZULFI AZ - ZAHRA", kelas: "XI-1" },
    { username: "nay127", password: "12345", nama: "NAYSILA DWI SASA BILA PUTRI SURYANTO", kelas: "XI-1" },
    { username: "naz674", password: "12345", nama: "NAZLAFATUL AZIZAH", kelas: "XI-1" },
    { username: "okt303", password: "12345", nama: "OKTA DWI NURAINI", kelas: "XI-1" },
    { username: "put833", password: "12345", nama: "PUTRI RIZQI RIA", kelas: "XI-1" },
    { username: "rer765", password: "12345", nama: "RERA MUSTIKA RESIMA", kelas: "XI-1" },
    { username: "ris818", password: "12345", nama: "RISMA AINYN NAFIAH", kelas: "XI-1" },
    { username: "san658", password: "12345", nama: "SANDY VIRZATULLAH", kelas: "XI-1" },
    { username: "suc529", password: "12345", nama: "SUCI LINTANG KINASIH", kelas: "XI-1" },
    { username: "van325", password: "12345", nama: "VANESA SEPTIANA PUTRI", kelas: "XI-1" },
    { username: "yor559", password: "12345", nama: "YORIZA DANISH SILVIERRA", kelas: "XI-1" },
    { username: "zel703", password: "12345", nama: "ZELIH AURELA", kelas: "XI-1" },
    { username: "amm384", password: "12345", nama: "AMMAR SAHADAT DIRGANTARA", kelas: "XI-1" },

    // KELAS XI-2
    { username: "alf928", password: "12345", nama: "ALFIDA HILDANA APRILIA", kelas: "XI-2" },
    { username: "ame990", password: "12345", nama: "AMELIA NG JIAXIN", kelas: "XI-2" },
    { username: "ang106", password: "12345", nama: "ANGGUN VIRMA VIRNANDA DEVI", kelas: "XI-2" },
    { username: "ann877", password: "12345", nama: "ANNISA PUTRI ZHAKI", kelas: "XI-2" },
    { username: "avi925", password: "12345", nama: "AVIZA KIRANA PUTRI", kelas: "XI-2" },
    { username: "dea263", password: "12345", nama: "DEA NOVA LEONA DEWI", kelas: "XI-2" },
    { username: "din814", password: "12345", nama: "DINDA SEPTYANA DEWI", kelas: "XI-2" },
    { username: "div532", password: "12345", nama: "DIVA ALICIA PUTRI", kelas: "XI-2" },
    { username: "eka448", password: "12345", nama: "EKA RESA RAMADHANI", kelas: "XI-2" },
    { username: "feb384", password: "12345", nama: "FEBY PUTRI SUGIANSYAH", kelas: "XI-2" },
    { username: "fel259", password: "12345", nama: "FELCIA AGASI", kelas: "XI-2" },
    { username: "gey320", password: "12345", nama: "GEYSA HASTA SAPUTRA", kelas: "XI-2" },
    { username: "i g881", password: "12345", nama: "I GEDE PUTRA YASA", kelas: "XI-2" },
    { username: "kay444", password: "12345", nama: "KAYLA MARETHA PUTRI PUSPITARINI", kelas: "XI-2" },
    { username: "key204", password: "12345", nama: "KEYSHA ANINDITA", kelas: "XI-2" },
    { username: "len194", password: "12345", nama: "LENNY ZHIFILIA NUGRAHANI", kelas: "XI-2" },
    { username: "mey489", password: "12345", nama: "MEYKA NINDI AGUSTIN", kelas: "XI-1" },
    { username: "moh199", password: "12345", nama: "MOHAMMAD NATA MAURINO", kelas: "XI-2" },
    { username: "moh467", password: "12345", nama: "MOHAMAD ANDRIAN MAULANA", kelas: "XI-2" },
    { username: "muh967", password: "12345", nama: "MUHAMMAD IBRAHIMMOVIC", kelas: "XI-2" },
    { username: "muh452", password: "12345", nama: "MUHAMMAD WAHYU PUJI NUGRAHA", kelas: "XI-2" },
    { username: "muz718", password: "12345", nama: "MUZDHALIFA", kelas: "XI-2" },
    { username: "nad370", password: "12345", nama: "NADIFAH FARHANATUL MABRUROH", kelas: "XI-2" },
    { username: "nen926", password: "12345", nama: "NENG AYU JAVANZA QUINE YUANDRI", kelas: "XI-2" },
    { username: "rev144", password: "12345", nama: "REVY MAULIDA HASANAH", kelas: "XI-2" },
    { username: "ris847", password: "12345", nama: "RISKA MAULIDA ULFA", kelas: "XI-2" },
    { username: "rob570", password: "12345", nama: "ROBY JATI MURTI", kelas: "XI-2" },
    { username: "sen227", password: "12345", nama: "SENJA DINANTI", kelas: "XI-2" },
    { username: "sof487", password: "12345", nama: "SOFYAN ZAHURI A.", kelas: "XI-2" },
    { username: "van180", password: "12345", nama: "VANA AGISTA RAMADHANI", kelas: "XI-2" },
    { username: "wul665", password: "12345", nama: "WULIDATUL AFIFAH", kelas: "XI-2" },
    { username: "yen400", password: "12345", nama: "YENI DWI PRASTIYANI", kelas: "XI-2" },
    { username: "mss949", password: "12345", nama: "M. SUELTAN SOFYAN ARRIDHO", kelas: "XI-2" },

    // KELAS XI-3
    { username: "ach743", password: "12345", nama: "ACHMAD FAIRUS RADITYA", kelas: "XI-3" },
    { username: "ald733", password: "12345", nama: "ALDERIO ILHAM QODZAFI", kelas: "XI-3" },
    { username: "alv982", password: "12345", nama: "ALVIAN MA'RIFATUL  ABROR", kelas: "XI-3" },
    { username: "ami470", password: "12345", nama: "AMIRAL JORDAN ARVA", kelas: "XI-3" },
    { username: "asy691", password: "12345", nama: "ASYAFA ZAHRA SALSABILLA", kelas: "XI-3" },
    { username: "aur296", password: "12345", nama: "AURA KIRANA MAULIDA", kelas: "XI-3" },
    { username: "che821", password: "12345", nama: "CHEISYA ANJELA PUTRI", kelas: "XI-3" },
    { username: "che171", password: "12345", nama: "CHEN LIXIN NUR ZASKIA", kelas: "XI-3" },
    { username: "daf146", password: "12345", nama: "DAFA PARVAIZ Z.W", kelas: "XI-3" },
    { username: "dim777", password: "12345", nama: "DIMAS MAULANA", kelas: "XI-3" },
    { username: "dis333", password: "12345", nama: "DISTY EKA FEBIANA", kelas: "XI-3" },
    { username: "dit891", password: "12345", nama: "DITA KHARISMA DEWI", kelas: "XI-3" },
    { username: "div396", password: "12345", nama: "DIVA PUSPITA SARI", kelas: "XI-3" },
    { username: "fat181", password: "12345", nama: "FATHIR LANANG YOGATAMA", kelas: "XI-3" },
    { username: "fit975", password: "12345", nama: "FITRI NUR AINI", kelas: "XI-3" },
    { username: "fiz338", password: "12345", nama: "FIZA ARIF UQIANUS FAN", kelas: "XI-3" },
    { username: "fri987", password: "12345", nama: "FRISYA MAULIDA SANTIKA", kelas: "XI-3" },
    { username: "iga203", password: "12345", nama: "IGA MAHAREZA", kelas: "XI-3" },
    { username: "m.d489", password: "12345", nama: "M.DANAR IZHA ROHIL", kelas: "XI-3" },
    { username: "may384", password: "12345", nama: "MAYLA AURA ANDINI", kelas: "XI-3" },
    { username: "moh564", password: "12345", nama: "MOH RIDHO DZIKRULLAH", kelas: "XI-3" },
    { username: "moh750", password: "12345", nama: "MOHAMAD ALFIAN MAULANA", kelas: "XI-3" },
    { username: "muh954", password: "12345", nama: "MUHAMMAD KHOIRON THOIFUR ABDILLAH", kelas: "XI-3" },
    { username: "mut473", password: "12345", nama: "MUTIARA DWI A", kelas: "XI-3" },
    { username: "nad266", password: "12345", nama: "NADIN SYA PRAWESTI", kelas: "XI-3" },
    { username: "put479", password: "12345", nama: "PUTRI BUNGA CAHYANI", kelas: "XI-3" },
    { username: "ram463", password: "12345", nama: "RAMADHAN", kelas: "XI-3" },
    { username: "ris314", password: "12345", nama: "RISKA NOVITA P", kelas: "XI-3" },
    { username: "sel786", password: "12345", nama: "SELVIA JUNITA", kelas: "XI-3" },
    { username: "shi373", password: "12345", nama: "SHINTA METTA L. M", kelas: "XI-3" },
    { username: "wul818", password: "12345", nama: "WULAN CEISHA RAMADANI", kelas: "XI-3" },
    { username: "moh799", password: "12345", nama: "MOHAMMAD RAFFI ALFARIDZI ARDIANSYAH", kelas: "XI-3" },
    { username: "akh763", password: "12345", nama: "AKHMAD FAUZI FADILAH", kelas: "XI-3" },
    { username: "moh173", password: "12345", nama: "MOHAMMAD ARYA RADITYA", kelas: "XI-3" },
    { username: "feb723", password: "12345", nama: "FEBRI ARDIANSYAH PUTRA", kelas: "XI-3" },

    // KELAS XI-4
    { username: "and750", password: "12345", nama: "ANDRIANU DWI PUTRA KUSUMA", kelas: "XI-4" },
    { username: "ang275", password: "12345", nama: "ANGGITA FITRI FAUZIAH", kelas: "XI-4" },
    { username: "aul646", password: "12345", nama: "AULIA ZULFALITQ  PRATAMA", kelas: "XI-4" },
    { username: "aur846", password: "12345", nama: "AUREL JIHAN PANESA", kelas: "XI-4" },
    { username: "cat350", password: "12345", nama: "CATUR AHMAD HASYIM", kelas: "XI-4" },
    { username: "cit267", password: "12345", nama: "CITRA AYU VERGITA", kelas: "XI-4" },
    { username: "dha573", password: "12345", nama: "DHANIEL ARIFIN", kelas: "XI-4" },
    { username: "dhe488", password: "12345", nama: "DHEA BUNGA APRILLIA", kelas: "XI-4" },
    { username: "fra376", password: "12345", nama: "FRANDA APRILA WURI HARTONO", kelas: "XI-4" },
    { username: "gan755", password: "12345", nama: "GANTARI ZIA BHUMYAMCA", kelas: "XI-4" },
    { username: "han804", password: "12345", nama: "HANA FITRIA", kelas: "XI-4" },
    { username: "hol670", password: "12345", nama: "HOLIDA TUL FITRI", kelas: "XI-4" },
    { username: "ich324", password: "12345", nama: "ICHA IZZATUL JANNAH", kelas: "XI-4" },
    { username: "ket801", password: "12345", nama: "KETUT SONY LOKE BUDI WIGUNA", kelas: "XI-4" },
    { username: "m.i432", password: "12345", nama: "M.IBRA RAVITO", kelas: "XI-4" },
    { username: "moh963", password: "12345", nama: "MOH AZIZUL HILMI", kelas: "XI-4" },
    { username: "moh886", password: "12345", nama: "MOHAMMAD TORIQ HIDAYAH", kelas: "XI-4" },
    { username: "muh894", password: "12345", nama: "MUHAMMAD ARTHA MAU RIDO", kelas: "XI-4" },
    { username: "moh157", password: "12345", nama: "MOHAMMAD VALE SEPTINO ROSSI", kelas: "XI-4" },
    { username: "nan334", password: "12345", nama: "NANDA SASMITA", kelas: "XI-4" },
    { username: "nay941", password: "12345", nama: "NAYLA MUFIDA", kelas: "XI-4" },
    { username: "pon132", password: "12345", nama: "PONI AGRIANDARI", kelas: "XI-4" },
    { username: "rak924", password: "12345", nama: "RAKA PUTRA ANGGARA", kelas: "XI-4" },
    { username: "ris423", password: "12345", nama: "RISTA AYU PUTRI", kelas: "XI-4" },
    { username: "sep510", password: "12345", nama: "SEPTIAN SURYA RHOMADHONI", kelas: "XI-4" },
    { username: "sya374", password: "12345", nama: "SYAVA DYANI PUTRI", kelas: "XI-4" },
    { username: "val167", password: "12345", nama: "VALECIA ANGGRAENI SASMITA. P.", kelas: "XI-4" },
    { username: "vie316", password: "12345", nama: "VIERRA DIPUSPA DESHINTA SUGIONO", kelas: "XI-4" },
    { username: "waw680", password: "12345", nama: "WAWENDRA WAHYU BIMARTA", kelas: "XI-4" },
    { username: "zah997", password: "12345", nama: "ZAHRA THUSITA", kelas: "XI-4" },
    { username: "zel835", password: "12345", nama: "ZELVIA AYU VERASARI", kelas: "XI-4" },
    { username: "nov422", password: "12345", nama: "NOVA WIDIANTI", kelas: "XI-4" },
    { username: "moh317", password: "12345", nama: "MOHAMMAD ARIANSYAH", kelas: "XI-4" },
    { username: "fir771", password: "12345", nama: "FIRDAUS IBNU HADU", kelas: "XI-4" },
    { username: "sal649", password: "12345", nama: "SALMA RAHADATUL AISY", kelas: "XI-4" },

    // KELAS XI-5
    { username: "adi611", password: "12345", nama: "ADITYA RAMADHANI", kelas: "XI-5" },
    { username: "air505", password: "12345", nama: "AIRA NAFISATUL AINIYAH", kelas: "XI-5" },
    { username: "ald758", password: "12345", nama: "ALDI KURNIAWAN  SAPUTRA", kelas: "XI-5" },
    { username: "and569", password: "12345", nama: "ANDIKA PRASETYA", kelas: "XI-5" },
    { username: "ant246", password: "12345", nama: "ANTONIO JUNIOR LIWA PUTRA", kelas: "XI-5" },
    { username: "bun371", password: "12345", nama: "BUNGA RACHMATYAS MAHANI", kelas: "XI-5" },
    { username: "ces242", password: "12345", nama: "CESYA MAWRA PAWLINA SARI", kelas: "XI-5" },
    { username: "eko352", password: "12345", nama: "EKO HARIANTO", kelas: "XI-5" },
    { username: "era862", password: "12345", nama: "ERA FATRAVIA", kelas: "XI-5" },
    { username: "gei674", password: "12345", nama: "GEISHA DWI APRILIA", kelas: "XI-5" },
    { username: "gin651", password: "12345", nama: "GINA JIFARA WANGI", kelas: "XI-5" },
    { username: "kev369", password: "12345", nama: "KEVIN JULIANO SANDRA PRATAMA", kelas: "XI-5" },
    { username: "kik864", password: "12345", nama: "KIKI ROSA K", kelas: "XI-5" },
    { username: "lin698", password: "12345", nama: "LINDA TRI YULIYANI", kelas: "XI-5" },
    { username: "lut538", password: "12345", nama: "LUTFI ARIL PRAYOGA", kelas: "XI-5" },
    { username: "mau697", password: "12345", nama: "MAULANA ISHAK", kelas: "XI-5" },
    { username: "mey508", password: "12345", nama: "MEYLANIE ANGGI ZAZIVA", kelas: "XI-5" },
    { username: "moh470", password: "12345", nama: "MOH FAKHRI LUTFI", kelas: "XI-5" },
    { username: "muh324", password: "12345", nama: "MUH AFREZA SAPUTRA", kelas: "XI-5" },
    { username: "muh241", password: "12345", nama: "MUHAMMAD SAFI' I", kelas: "XI-5" },
    { username: "nau621", password: "12345", nama: "NAURA GELICIA T.", kelas: "XI-5" },
    { username: "nur605", password: "12345", nama: "NURUL IZZATI", kelas: "XI-5" },
    { username: "rah193", password: "12345", nama: "RAHMA INTAN PERMADHANI", kelas: "XI-5" },
    { username: "rah873", password: "12345", nama: "RAHMA TAUFIK RIDANI", kelas: "XI-5" },
    { username: "reg148", password: "12345", nama: "REGA TEGAR MAULANA HAKIKI", kelas: "XI-5" },
    { username: "saf981", password: "12345", nama: "SAFA TIARA", kelas: "XI-5" },
    { username: "ste212", password: "12345", nama: "STEFA RINA PUTRI ANINDITA", kelas: "XI-5" },
    { username: "ste256", password: "12345", nama: "STEFANI ANGELINA DARMANOTA", kelas: "XI-5" },
    { username: "sul742", password: "12345", nama: "SULUH PRABANDARU", kelas: "XI-5" },
    { username: "sye263", password: "12345", nama: "SYERILA SILFI MAULIDA", kelas: "XI-5" },
    { username: "tia911", password: "12345", nama: "TIARA AYU SABRINA", kelas: "XI-5" },
    { username: "wah796", password: "12345", nama: "WAHYU RIZKY", kelas: "XI-5" },
    { username: "yuy532", password: "12345", nama: "YUYUN ALFIANA", kelas: "XI-5" },
    { username: "nag710", password: "12345", nama: "NAGITA NUR OKTAVIANI", kelas: "XI-5" },
    { username: "dil165", password: "12345", nama: "DILA AGUS TIYA NEGSEH", kelas: "XI-5" },
    { username: "gyt494", password: "12345", nama: "GYTHA ATHIVA QANITA AZARIA", kelas: "XI-5" },

    // KELAS XI-6
    { username: "ach490", password: "12345#", nama: "ACHAVA PUTRI ARIFANI", kelas: "XI-6" },
    { username: "ang710", password: "12345#", nama: "ANGGUN TRI MULYANI", kelas: "XI-6" },
    { username: "ary579", password: "12345#", nama: "ARYAN DWI NURBEKTI", kelas: "XI-6" },
    { username: "bay641", password: "12345#", nama: "BAYU PUTRA RAMADHAN", kelas: "XI-6" },
    { username: "cah357", password: "12345#", nama: "CAHYARANI FATUROHMAH", kelas: "XI-6" },
    { username: "dha666", password: "12345#", nama: "DHANIEL ARIFIN", kelas: "XI-6" },
    { username: "fah981", password: "12345#", nama: "FAHRIZAL BAHTIAR HAMZAH", kelas: "XI-6" },
    { username: "fah111", password: "12345#", nama: "FAHZA ALIYA PUTRI", kelas: "XI-6" },
    { username: "faz796", password: "12345#", nama: "FAZA ASKIA TAMMA", kelas: "XI-6" },
    { username: "fel838", password: "12345#", nama: "FELIZA ARTHA JASMINE", kelas: "XI-6" },
    { username: "fer217", password: "12345#", nama: "FERDY ID ANDRE YANTO", kelas: "XI-6" },
    { username: "gal798", password: "12345#", nama: "GALUH SAPUTRI", kelas: "XI-6" },
    { username: "jes649", password: "12345#", nama: "JESSI TIRTA DHARMA AYU PUSPA  YOGI", kelas: "XI-6" },
    { username: "lav868", password: "12345#", nama: "LAVENIA VEGA PUTRI MANIK", kelas: "XI-6" },
    { username: "m a373", password: "12345#", nama: "M ANDY BEGARRT PRASSETYO", kelas: "XI-6" },
    { username: "m p887", password: "12345#", nama: "M PRIYA DANIEL W", kelas: "XI-6" },
    { username: "mar756", password: "12345#", nama: "MARSYA DWI SAPUTRI", kelas: "XI-6" },
    { username: "moh448", password: "12345#", nama: "MOH ARLYN DWI ANDIKA", kelas: "XI-6" },
    { username: "moh214", password: "12345#", nama: "MOH DANIAL HERDYANSAH", kelas: "XI-6" },
    { username: "moh400", password: "12345#", nama: "MOH RAFKA EKA MANNANSYAH", kelas: "XI-6" },
    { username: "moh545", password: "12345#", nama: "MOH RIFKI NUR HIDAYAT", kelas: "XI-6" },
    { username: "moh261", password: "12345#", nama: "MOHAMAD FAHREZI", kelas: "XI-6" },
    { username: "put564", password: "12345#", nama: "PUTRI AURA MARGARETA", kelas: "XI-6" },
    { username: "rah103", password: "12345#", nama: "RAHEL NILUH AGUSTINA", kelas: "XI-6" },
    { username: "ram839", password: "12345#", nama: "RAMADHANI TEGAR PAMUJI", kelas: "XI-6" },
    { username: "rey996", password: "12345#", nama: "REYNO ARVENTA HADIN PRATAMA", kelas: "XI-6" },
    { username: "sas836", password: "12345#", nama: "SASKIA PUTRI CAHYANINGTYAS", kelas: "XI-6" },
    { username: "sep369", password: "12345#", nama: "SEPTINA AULIYA RAMADANI", kelas: "XI-6" },
    { username: "sey612", password: "12345#", nama: "SEYLA ERFA AMANDA PUTRI", kelas: "XI-6" },
    { username: "sof880", password: "12345#", nama: "SOFIATUL AZIZAH", kelas: "XI-6" },
    { username: "wan282", password: "12345#", nama: "WANDA PUTRI", kelas: "XI-6" },
    { username: "din619", password: "12345#", nama: "DINDA SEKAR RUMI", kelas: "XI-6" },
    { username: "alv208", password: "12345#", nama: "ALVINO GANESHA PUTRA", kelas: "XI-6" },
    { username: "myi991", password: "12345#", nama: "MYISHA AMELIA JAUHARI", kelas: "XI-6" },
    { username: "wif740", password: "12345#", nama: "WIFA RIZKI RAMADANI", kelas: "XI-6" },
    { username: "wid405", password: "12345#", nama: "WIDYA JULITA SAPUTRI", kelas: "XI-6" },
    { username: "ayu113", password: "12345#", nama: "AYU ALFIYANTI", kelas: "XI-6" }
];
